### PR TITLE
QuicTokenHandler: expose max connection id length, fix endianness

### LINKED ISSUE #731: `QuicTokenHandler` receives buffers of different endianness
**Version:** ~0.0.64.Final~  0.0.65.Final

`QuicTokenHandler` receives swapped byte buffer in `writeToken`, but a regular buffer in `validateToken`.

This could give you a lot of debugging time figuring out why none of the `readInt`, `writeInt` and similar functions works correctly.

### PR DESCRIPTION
**Pull request by makkarpov**
Fixes #731.

* Ensures that all buffers passed to the `QuicTokenHandler` are now big endian
* `Quiche.MAX_TOKEN_LEN` is exposed to the outside world via `QuicTokenHandler.maxConnectionIdLength()`

### CODE REVIEW

File: codec-classes-quic/src/main/java/io/netty/incubator/codec/quic/QuicTokenHandler.java [hunk 1]
```diff
@@ -51,4 +51,9 @@ public interface QuicTokenHandler {
      * @return the maximal supported token length.
      */
     int maxTokenLength();
+
+    /** @return Maximum possible length of the {@code dcid} buffer passed to {@link #writeToken} method */
+    static int maxConnectionIdLength() {
```
Comment (normanmaurer) [inline codec-classes-quic/src/main/java/io/netty/incubator/codec/quic/QuicTokenHandler.java:56]: I think we should better not use `Quiche.*` within here as it might result into problems when the native lib is not loaded.

**Review by normanmaurer — CHANGES_REQUESTED** [review]

File: codec-classes-quic/src/main/java/io/netty/incubator/codec/quic/QuicTokenHandler.java (hunk 1 above)
Comment (makkarpov) [reply codec-classes-quic/src/main/java/io/netty/incubator/codec/quic/QuicTokenHandler.java:56]: But same kind of problems will arise when `InsecureQuicTokenHandler` is instantiated. What are the other alternatives?

This definitely should be exposed one way or another, otherwise it is impossible to write any third-party implementation for the `QuicTokenHandler` cleanly. You need that to calculate the maximum token size.

**Comment by normanmaurer** [comment]
@makkarpov PTAL

**Comment by normanmaurer** [comment]
@makkarpov did you sign our icla ? https://netty.io/s/icla

**Comment by makkarpov** [comment]
Signed it now

**Comment by normanmaurer** [comment]
Thanks a lot @makkarpov
